#!/bin/bash

apt install dialog
uname -m | grep aarch64
if [ "$?" -ne 0 ]
then 
dialog --title "Error" --msgbox "32 bit system cant install xmrig" 5 36
clear
exit
fi
apt update -y
apt upgrade -y
apt install wget -y
apt install proot -y
apt install git -y
apt install build-essential -y
apt install cmake -y
git clone https://github.com/xmrig/xmrig.git

temp=$(mktemp -t temp.XXXXXX)
sed -e '
s/kDefaultDonateLevel = 1/kDefaultDonateLevel = 0/
s/kMinimumDonateLevel = 1/kMinimumDonateLevel = 0/' xmrig/src/donate.h > "$temp"
 
cp "$temp" xmrig/src/donate.h

mkdir xmrig/build
cd xmrig/build

clear

dialog --title "Xmrig Installation" \
--menu "Choose Install Type" 9 38 2 \
1 "Minimal Install (Monero/XMR)" \
2 "Full Install (all algos)" 2> "$temp"
clear
if [ $(cat "$temp") -eq 1 ]
then
cmake .. -DWITH_HWLOC=OFF -DWITH_CN_LITE=OFF -DWITH_CN_HEAVY=OFF -DWITH_CN_PICO=OFF \
 -DWITH_CN_FEMTO=OFF -DWITH_ARGON2=OFF -DWITH_ASTROBWT=OFF \
 -DWITH_KAWPOW=OFF -DWITH_OPENCL=OFF -DWITH_CUDA=OFF -DWITH_MSR=OFF \
 -DWITH_SSE4_1=OFF -DWITH_BENCHMARK=OFF  -DWITH_GHOSTRIDER=OFF
else cmake .. -DWITH_HWLOC=OFF
fi
rm -f "$temp" 2> /dev/null
make -j$(nproc)
cd
ln -s xmrig/build/xmrig start_xmrig
curl -LO https://github.com/ioprojecton/xmrig/tarball/master
tar -xzvf master
rm master
cd io*
cp miner.tgz ~
cd
rm -rf io*
tar -zxvf miner.tgz
exit
