#!/bin/bash

search_for_string(){
echo "$(grep -n $1 $2)"
}

search_line_number(){
while read -d ":" word
do
line_num="$word"
done < <(echo "$1")
echo "$line_num"
}

uname -m | grep aarch64
if [ "$?" -ne 0 ]
then echo "32 bit system cant install xmrig"
exit
fi
apt update -y
apt upgrade -y
apt install wget -y
apt install proot -y
apt install git -y
apt install build-essential -y
apt install cmake -y
apt install dialog
git clone https://github.com/xmrig/xmrig.git

donate_default=$(search_for_string "kDefaultDonateLevel" "xmrig/src/donate.h")
donate_minimum=$(search_for_string "kMinimumDonateLevel" "xmrig/src/donate.h")

donate_default_line=$(search_line_number "$donate_default")
donate_minimum_line=$(search_line_number "$donate_minimum")

i=1
while read line
do
if [ "$i" -eq "$donate_default_line" ]
then echo "constexpr const int kDefaultDonateLevel = 0;"
elif [ "$i" -eq "$donate_minimum_line" ]
then echo "constexpr const int kMinimumDonateLevel = 0;"
else echo "$line"
fi
((i++))
done < xmrig/src/donate.h > xmrig/src/newDonate.h
rm xmrig/src/donate.h
mv xmrig/src/newDonate.h xmrig/src/donate.h

mkdir xmrig/build
cd xmrig/build

clear
echo
echo -e "\t\tChoose install type"
echo
echo -n "1.Minimal install (Monero/XMR)"
echo -e "\t2.Full install"
echo
echo -en "\t\t\tType: "

read -n 1 type
echo
if [ "$type" -eq 1 ]
then
cmake .. -DWITH_HWLOC=OFF -DWITH_CN_LITE=OFF -DWITH_CN_HEAVY=OFF -DWITH_CN_PICO=OFF \
 -DWITH_CN_FEMTO=OFF -DWITH_ARGON2=OFF -DWITH_ASTROBWT=OFF \
 -DWITH_KAWPOW=OFF -DWITH_OPENCL=OFF -DWITH_CUDA=OFF -DWITH_MSR=OFF \
 -DWITH_SSE4_1=OFF -DWITH_BENCHMARK=OFF  -DWITH_GHOSTRIDER=OFF
else cmake .. -DWITH_HWLOC=OFF
fi
make -j$(nproc)
cd
ln -s xmrig/build/xmrig start_xmrig
exit
